---
title: "R packages"
date: "`r paste0(format(Sys.time(), '%d %B %Y'))`"
author: 'Kevin Cazelles, post-doc, McCann Lab, [<i class="fa fa-github" aria-hidden="true"></i>](https://github.com/KevCaz/aboutRPackages)'
output:
  ioslides_presentation:
    incremental: true
    widescreen: true
    includes:
      in_header: kcheader.html
      #logo: ./img/logo.png
---



# R / RStudio / CRAN

## R / RStudio / CRAN

R: https://www.r-project.org/

RStudio: https://www.rstudio.com/

CRAN: https://cran.r-project.org/mirrors.html

BioConductor: http://www.bioconductor.org/

MetaCRAN: https://www.r-pkg.org/

More: https://github.com/eddelbuettel/drat




# What is an R package?

## Definition

Quite tricky to answer! I would say:

> a set of files that passes the `R CMD install`



## Examples

- [png](https://cran.r-project.org/web/packages/png/index.html)

- [knitr](https://cran.r-project.org/web/packages/knitr/index.html): 188 functions

- [vegan](https://cran.r-project.org/web/packages/vegan/index.html): 103 functions (+425 non-exported function)

- [trump](https://github.com/romainfrancois/trump)


## Many packages

- http://blog.revolutionanalytics.com/2017/01/cran-10000.html

- 2012: article by Kurt Hornik (CRAN maintainer) http://www.stat.tugraz.at/AJS/ausg121/121Hornik.pdf



# Why would you create an R package?




# Action

## Create your R package without RStudio

```
package.skeleton()
```

<br>

https://cran.r-project.org/doc/manuals/r-release/R-exts.html


## Create your R package with RStudio

https://support.rstudio.com/hc/en-us/articles/200486488-Developing-Packages-with-RStudio

<br>

Must read: http://r-pkgs.had.co.nz/


## Package architecture

- `DESCRIPTION`: meta data of your package (name, version, ...)
- `NAMESPACE`: import / export / dynlab
- `R`: R functions
- `man`: documentation (`.Rd` files)

## Package architecture

- `data`: R objects stored as RData (`.rda`)
- `vignettes`: documentation
- `src`: file in other programming language
- `test`: tests for you package
- `inst`: CITATION / non-R scripts / external-data...
- `.Rbuildignore`
- `.Rinstignore`



# Session 2

## Remember

- `DESCRIPTION`: meta data of your package (name, version, ...)
- `NAMESPACE`: import / export / dynlab
- `R`: R functions
- `man`: documentation (`.Rd` files)
- `test`: tests (`.R` files)
- `data`: data (`.Rda` files)


## Hadley's package collection for package development

- [R packages](http://r-pkgs.had.co.nz/)
- Devtools: `install.packages('devtools')`
- Roxygen: to document package
- Testhat: to test your package
- Rmarkdown: to build vignettes



## Basic workflow with `devtools`

- create a function `load_all()`
- document the function `document()`
- test the function `test()`

## `load_all()`

First, create a function. For instance I've created:

```{r, eval=FALSE}
getDigits <- function(x, collapse = NULL) {
    out <- strsplit(x, split = "\\D") %>% lapply(function(x) x[x != ""])
    if (!is.null(collapse))
        out <- lapply(out, paste, collapse = collapse)
    out
}
```

in `R/getDigits.R` file.

## `load_all()`

<video width="90%" controls>
 <source src="img/load_all.webm" type="video/webm">
 Your browser does not support the video tag.
</video>

## Additional tools to improve your workflow

- Web-based version control repository hosting service:
  - [Github](https://github.com/)
  - [Bitbucket](https://bitbucket.org/)

- Continuous Integration
  - [Travis](https://travis-ci.org/)
  - [Appveyor](https://www.appveyor.com/)

- Code quality (*i.e.* code coverage)
  - [Codecov](https://codecov.io/gh)
  - [Codeclimate](https://codeclimate.com/)


## Versioning and Licence

- [Semantic versioning](https://semver.org/)
- [Choose a license](https://choosealicense.com/)




<!-- ## cool

<div class="centered">
This text is centered.
</div>

## cool2

<div class="columns-2">

  - Bullet 1
  - Bullet 2
  - Bullet 3
</div> -->
